In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000_000)
my_list = list(range(1000_000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 62.6 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.53 s


In [5]:
data = np.random.randn(2,3)

In [6]:
data

array([[ 1.42838927,  1.05767581,  1.2814465 ],
       [-0.69412448,  0.04057091,  1.10528897]])

In [7]:
data * 10

array([[14.28389271, 10.57675815, 12.81446502],
       [-6.94124476,  0.40570905, 11.05288969]])

In [8]:
data+data

array([[ 2.85677854,  2.11535163,  2.562893  ],
       [-1.38824895,  0.08114181,  2.21057794]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

In [11]:
arr = np.empty((8,4))

In [12]:
arr

array([[2.11e-321, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000]])

In [13]:
for i in range(8):
    arr[i] = i

In [14]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [15]:
arr[4,3,2]

IndexError: too many indices for array

In [16]:
arr[[4,3,2]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [2., 2., 2., 2.]])

In [17]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [18]:
arr = np.arange(32).reshape(8,4)

In [19]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [20]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])